---
title: "MIPS_Data"
output: html_notebook
---

This is the initial Import and cleanup of the Physician file before uploading the file to s3 for use in an EMR cluster.

```{r}
# Import Libraries
library(gapminder)
library(DataExplorer)
library(tidyverse)
library(dplyr)
library(aws.s3)
```

## Import MIPS Data for EDA:
```{r}
MIPS <- read.csv('Data/Physician_Compare_2017_Individual_EC_Public_Reporting-Overall_MIPS_Performance.csv', header = T)

```
```{r}
#Show what the values are for each column
plot_str(MIPS)
```
```{r}
#Plot missing values
plot_missing(MIPS)
```
```{r}
# New variable with cleaned missing rows
new_MIPS <- na.omit(MIPS)
plot_missing(new_MIPS)
```
```{r}
#Histogram of continuous variables
plot_histogram(new_MIPS)
```

```{r}
# Density of continuous variables
plot_density(new_MIPS)
```
```{r}
# Bar Plot of categorical variables
plot_bar(new_MIPS) 
```
```{r}
# Write cleaned data to csv
file_name = "Cleaned_Compare.csv"
write.csv(new_MIPS, file = file_name)

```
```{r}

Sys.setenv("AWS_ACCESS_KEY_ID" = "",
           "AWS_SECRET_ACCESS_KEY" = "")


# Upload file to s3
bucketlist()
put_object(file_name, object = "Cleaned_MIPS.csv", bucket = "medicare-mips")
```


































